@startuml blackboardController
autonumber

actor Player order 10
participant "PlayerInteractionController" as PIC order 20
participant "BlackboardController" as BBC order 50
participant "InfoBoxManager" as IBM order 60
participant "FileBrowserUpdate" as FBU order 70
participant "VideoWithAudio" as VWA order 80
participant "VideoPlayer" as VP order 90
participant "CurrentBlackBoard" as BB order 100

activate PIC
PIC -> BBC: interact()
activate BBC

BBC -> IBM: ShowText(blackboardInteractionKey)
activate IBM
IBM --> BBC
deactivate IBM

Player -> BBC: Presses "E"

BBC -> FBU: OpenFileBrowser()
activate FBU
FBU --> BBC: Return File path
deactivate FBU


BBC -> BBC: DisplayOnBlackboard(path)
BBC -> BB: changeVideo() / changeImg() / changePDF()
activate BB
BB --> BBC
deactivate BB

BBC --> PIC
deactivate BBC

PIC -> BBC: interact()
activate BBC

BBC -> IBM: ShowText(blackboardInteractionKey)
activate IBM
IBM --> BBC
deactivate IBM

Player -> BBC: Presses "P"

BBC -> VWA: Play()/Pause()
activate VWA

VWA -> VP: Play()/Pause()
activate VP
VP --> BB: "Plays/Pauses Video on Blackboard"
activate BB
VP --> VWA
deactivate VP

VWA --> BBC
deactivate VWA
BBC --> PIC
deactivate BBC

deactivate PIC
@enduml