@startuml blackboardController
autonumber

actor "User" as Player order 10
participant "PlayerInteractionController" as PIC order 20
participant "Blackboard" as BBC order 50
participant "InfoBoxManager" as IBM order 60
participant "FileBrowserUpdate" as FBU order 70
participant "VideoWithAudio" as VWA order 80
participant "VideoPlayer" as VP order 90
participant "UnityWebRequestTexture" as UWR order 100

activate PIC
PIC -> BBC: interact()
activate BBC

BBC -> IBM: ShowText(blackboardInteractionKey)
activate IBM
IBM --> BBC
deactivate IBM

alt User chooses files to display
Player -> BBC: Presses "E"
BBC -> FBU: OpenFileBrowser(callback:DisplayOnBlackboard())
activate FBU
FBU --> BBC: DisplayOnBlackBoard(file paths)
deactivate FBU

alt User chose an image
    BBC -> UWR : getTexture(path)
    activate UWR
    UWR --> BBC : texture
    deactivate UWR
    BBC -> BBC : Change texture of the plane
else User chose a video
    BBC -> VWA : changeVideo(path)
    activate VWA
    VWA -> VP : Set new file url
    VWA -> VP : Play()
    activate VP
    VP --> VWA
    deactivate VP
    VWA --> BBC
    deactivate VWA
end

BBC --> PIC
deactivate BBC

else User pauses/resumes a video
Player -> BBC: Presses "P"
activate BBC

BBC -> VWA: Play()/Pause()
activate VWA

VWA -> VP: Play()/Pause()
activate VP

VP --> VWA
deactivate VP

VWA --> BBC
deactivate VWA
BBC --> PIC
deactivate BBC

deactivate PIC
end

@enduml