@startuml DoorController
autonumber

actor Player order 10

box "Client Machine" #555555
participant "PlayerInteractionController" as PIC order 20
participant "DoorInteraction" as DIC order 50
participant "InfoBoxManager" as IBM order 60
end box

box "Server Machine" #777777
participant "PlayerNetwork" as PN order 70
participant "DoorInteraction" as DIH order 80
end box

Player -> Player: Turn camera to a door

PIC -> DIC: interact()
activate PIC 
activate DIC

DIC -> IBM: ShowText(doorInteractKey)
activate IBM
IBM --> DIC
deactivate IBM

Player -> DIC: Presses "E"

DIC -> PN: toggleDoorServerRpc()
activate PN
PN -> DIH: toggleDoor()
activate DIH
DIH --> PN
deactivate DIH
PN --> DIC
deactivate PN


DIC --> PIC
deactivate DIC

deactivate PIC
@enduml