@startuml
component host
component client
component relay
component unityServers

unityServers <-d-> host
unityServers <-d-> relay
unityServers <-d-> client


host <-r-> relay
relay <-r-> client
@enduml