@startuml
!theme vibrant

component Scene #FFAAAA
component Player #AAAAFF
component NetworkManagerObject as "NetworkManager (obj)" #FFAAAA
component VivoxVoiceManagerObject as "VivoxVoiceManager (obj)" #FFAAAA

package "Overlay UI" {
  component UIDocument #FFAAAA
  component Canvas #FFAAAA
}
component Controllers #FFAAAA

component BlackboardObject as "Blackboard (obj)" #FFAAAA
component BlackboardScript as "Blackboard (script)" #AAFFAA
component Plane #FFAAAA
component VideoWithAudio #AAFFAA
component FileBrowserUpdate #AAFFAA



component Facultad #FFAAAA
component MainCamera #FFAAAA
component GlobalScripts #FFAAAA

package "Network elements" {
  component NetworkObject #AAFFAA
  component NetworkTransform #AAFFAA
  component ClientNetworkTransform #AAFFAA
}

component PlayerNetwork #AAFFAA

component PlayerControllers #AAFFAA
component PlayerMovementController #AAFFAA
component PlayerInteractionController #AAFFAA
component DoorInteraction #AAFFAA

component TestRelay #AAFFAA
component Door #AAAAFF

component MainGui #AAFFAA
component VideoSelectorBoxManager #AAFFAA
component InfoBoxManager #AAFFAA
component ConnectBoxManager #AAFFAA

component InGameDebugConsole #FFAAAA
component DebugLogManager #AAFFAA

component NetworkManagerScript as "NetworkManager (script)" #AAFFAA
component UnityTransport #AAFFAA
component VivoxPlayer #AAFFAA

component VivoxVoiceManagerScript as "VivoxVoiceManager (script)" #AAFFAA


'First line ordering
Controllers -[hidden]r-> Player
Player -[hidden]r-> Facultad
'NetworkManagerObject -[hidden]r-> NetworkManagerObject
'NetworkManager -[hidden]r-> VivoxVoiceManager
'VivoxVoiceManager -[hidden]r-> Canvas
'Canvas -[hidden]r-> UIDocument
'UIDocument -[hidden]r-> Player



NetworkTransform <|-- ClientNetworkTransform

Scene *-- Player
Scene *-- NetworkManagerObject
Scene *-- VivoxVoiceManagerObject
Scene *-- UIDocument
Scene *-- Canvas
Scene *-- Facultad
Scene *-- MainCamera
Scene *-- GlobalScripts
Scene *-- Controllers

Facultad *-- BlackboardObject
BlackboardObject *-- BlackboardScript
BlackboardObject *-- Plane
Plane *-- VideoWithAudio
Plane *-- FileBrowserUpdate

Player *-- NetworkObject
Player *-- ClientNetworkTransform
Player *-- PlayerNetwork
PlayerNetwork ..> PlayerControllers : Creates if owner

GlobalScripts *-- TestRelay

Facultad *-- Door
Door *-- DoorInteraction
Door *-- NetworkObject
Door *-- NetworkTransform

UIDocument *-- MainGui
MainGui *-- VideoSelectorBoxManager
MainGui *-- InfoBoxManager
MainGui *-- ConnectBoxManager

Canvas *-- InGameDebugConsole
InGameDebugConsole *-- DebugLogManager

NetworkManagerObject *-- NetworkManagerScript
NetworkManagerObject *-- VivoxPlayer
NetworkManagerObject *-- UnityTransport
VivoxVoiceManagerObject *-- VivoxVoiceManagerScript

Controllers o-- PlayerControllers
PlayerControllers *-- PlayerMovementController
PlayerControllers *-- PlayerInteractionController

@enduml